error: Closure called just once immediately after it was declared
  --> $DIR/redundant_closure_call.rs:12:5
   |
LL |     i = closure();
   |     ^^^^^^^^^^^^^
   |
   = note: `-D clippy::redundant-closure-call` implied by `-D warnings`

error: Closure called just once immediately after it was declared
  --> $DIR/redundant_closure_call.rs:15:5
   |
LL |     i = closure(3);
   |     ^^^^^^^^^^^^^^

error: Try not to call a closure in the expression where it is declared.
  --> $DIR/redundant_closure_call.rs:7:17
   |
LL |     let mut k = (|m| m + 1)(i);
   |                 ^^^^^^^^^^^^^^

error: Try not to call a closure in the expression where it is declared.
  --> $DIR/redundant_closure_call.rs:9:9
   |
LL |     k = (|a, b| a * b)(1, 5);
   |         ^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

